# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/fuxi/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),fuxi)

$(call add-radio-file-sha1-checked,radio/abl.img,a4420fcfe94688258a88d8e4fc2e72e832008856)
$(call add-radio-file-sha1-checked,radio/aop.img,5155733caf76955902114b78c3722496194135a4)
$(call add-radio-file-sha1-checked,radio/aop_config.img,52292b98804eefd76cfdfe862104c029ae19e784)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,f443ca9e8458d81e76cae7ffb0146f46d93ac127)
$(call add-radio-file-sha1-checked,radio/cpucp.img,9d54de26cdc87f2d6a3d7255784962f0476cd823)
$(call add-radio-file-sha1-checked,radio/devcfg.img,c13433bdebca945aede279f71457eed30b57cb29)
$(call add-radio-file-sha1-checked,radio/dsp.img,f9c9b38118a3cbc1beae8827c35a8e43ef05699e)
$(call add-radio-file-sha1-checked,radio/featenabler.img,a56ece7fcb4765754ab50fb6f66b570f0d441598)
$(call add-radio-file-sha1-checked,radio/hyp.img,c1e15adf8624d6c57d8b872634c529c64fd3d526)
$(call add-radio-file-sha1-checked,radio/imagefv.img,9fbbda21194fe45f0c350d254c1262d7d9424d20)
$(call add-radio-file-sha1-checked,radio/keymaster.img,9797ff49d54cb9b83a8e02b8815a3a155a3d101a)
$(call add-radio-file-sha1-checked,radio/modem.img,7c8c66ff882fc89438c920ae32ea64c9728cfec4)
$(call add-radio-file-sha1-checked,radio/qupfw.img,ee2f9529130173dbeb8e1471d0145402c9910bf9)
$(call add-radio-file-sha1-checked,radio/shrm.img,ee4fda95a1ebcdc314017bfd21d14fcb30fb3591)
$(call add-radio-file-sha1-checked,radio/tz.img,b290f00d0c903e960768ffc31459cffd6d54abf4)
$(call add-radio-file-sha1-checked,radio/uefi.img,259db934c5709d0492fa2b1538d975691ef10df1)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,ce947c973e7a51fa1a1335eb42825a8fc5608258)
$(call add-radio-file-sha1-checked,radio/xbl.img,caf179759006aa3e3a00d22ba0169c1495c5b9ff)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,066ec4b0ac2f2c7755614a62515e445cc44aa6d1)
$(call add-radio-file-sha1-checked,radio/xbl_ramdump.img,c6c5fa3901dba7d253cb09cba934d09789a4fbe7)

endif
